name = "FourierSeriesEvaluators"
uuid = "2a892dea-6eef-4bb5-9d1c-de966c9f6db5"
authors = ["lxvm <lorenzo@vanmunoz.com>"]
version = "0.1.0"

[deps]
AbstractFourierSeriesEvaluators = "0a142af0-e792-4045-9df2-39f854813ded"
